export enum FileTypeEnum {
  IMAGE = "IMAGE", VIDEO= "VIDEO", APPLICATION = "APPLICATION", AUDIO = "AUDIO", TEXT = "TXT", FOLDER = "FOLDER",
  DOC = "DOC", DOCX = "DOCX", PPT = "PPT", PPTX = "PPTX"
}
